using System.ComponentModel.DataAnnotations;

namespace DispatchManager.ViewModel
{
    public class TruckViewModel
    {
        public int Id { get; set; }
        [Required]
        public string TruckName { get; set; }
        public string VinNumber { get; set; }
        public string Capacity { get; set; }
        public string Odemetor { get; set; }
        public string SuggestedVIN { get; set; }
        public string ErrorCode { get; set; }
        public string PossibleValues { get; set; }
        public string AdditionalErrorText { get; set; }
        public string DestinationMarket { get; set; }
        public string Make { get; set; }
        public string ManufacturerName { get; set; }
        public string Model { get; set; }
        public string ModelYear { get; set; }
        public string PlantCity { get; set; }
        public string Series { get; set; }
        public string Trim { get; set; }
        public string VehicleType { get; set; }
        public string PlantCountry { get; set; }
        public string PlantCompanyName { get; set; }
        public string PlantState { get; set; }
        public string Trim2 { get; set; }
        public string Series2 { get; set; }
        public string Note { get; set; }
        public string BasePrice { get; set; }
        public string ManufacturerId { get; set; }
        public string CashForClunkers { get; set; }
        public string BodyClass { get; set; }
        public string Doors { get; set; }
        public string Windows { get; set; }
        public string WheelBaseType { get; set; }
        public string TrackWidth { get; set; }
        public string GrossVehicleWeightRating { get; set; }
        public string BedLengthinches { get; set; }
        public string CurbWeightpounds { get; set; }
        public string WheelBaseinches { get; set; }
        public string WheelBaseinchesupto { get; set; }
        public string BedType { get; set; }
        public string CabType { get; set; }
        public string TrailerTypeConnection { get; set; }
        public string TrailerBodyType { get; set; }
        public string TrailerLengthfeet { get; set; }
        public string OtherTrailerInfo { get; set; }
        public string NumberofWheels { get; set; }
        public string WheelSizeFrontinches { get; set; }
        public string WheelSizeRearinches { get; set; }
        public string EntertainmentSystem { get; set; }
        public string SteeringLocation { get; set; }
        public string NumberofSeats { get; set; }
        public string NumberofSeatRows { get; set; }
        public string TransmissionStyle { get; set; }
        public string TransmissionSpeeds { get; set; }
        public string DriveType { get; set; }
        public string Axles { get; set; }
        public string AxleConfiguration { get; set; }
        public string BrakeSystemType { get; set; }
        public string BrakeSystemDescription { get; set; }
        public string BatteryInfo { get; set; }
        public string BatteryType { get; set; }
        public string NumberofBatteryCellsperModule { get; set; }
        public string BatteryCurrentAmps { get; set; }
        public string BatteryVoltageVolts { get; set; }
        public string BatteryEnergyKWh { get; set; }
        public string EVDriveUnit { get; set; }
        public string BatteryCurrentAmpsupto { get; set; }
        public string BatteryVoltageVoltsupto { get; set; }
        public string BatteryEnergyKWhupto { get; set; }
        public string NumberofBatteryModulesperPack { get; set; }
        public string NumberofBatteryPacksperVehicle { get; set; }
        public string ChargerLevel { get; set; }
        public string ChargerPowerKW { get; set; }
        public string EngineNumberofCylinders { get; set; }
        public string DisplacementCC { get; set; }
        public string DisplacementCI { get; set; }
        public string DisplacementL { get; set; }
        public string EngineStrokeCycles { get; set; }
        public string EngineModel { get; set; }
        public string EnginePowerKW { get; set; }
        public string FuelTypePrimary { get; set; }
        public string ValveTrainDesign { get; set; }
        public string EngineConfiguration { get; set; }
        public string FuelTypeSecondary { get; set; }
        public string FuelDeliveryFuelInjectionType { get; set; }
        public string EngineBrakehp { get; set; }
        public string CoolingType { get; set; }
        public string EngineBrakehpupto { get; set; }
        public string ElectrificationLevel { get; set; }
        public string OtherEngineInfo { get; set; }
        public string Turbo { get; set; }
        public string TopSpeedMPH { get; set; }
        public string EngineManufacturer { get; set; }
        public string Pretensioner { get; set; }
        public string SeatBeltsType { get; set; }
        public string OtherRestraintSystemInfo { get; set; }
        public string CurtainAirBagLocations { get; set; }
        public string SeatCushionAirBagLocations { get; set; }
        public string FrontAirBagLocations { get; set; }
        public string KneeAirBagLocations { get; set; }
        public string SideAirBagLocations { get; set; }
        public string DriverAssist { get; set; }
        public string AdaptiveCruiseControlACC { get; set; }
        public string AdaptiveHeadlights { get; set; }
        public string AntilockBrakingSystemABS { get; set; }
        public string CrashImminentBrakingCIB { get; set; }
        public string BlindSpotDetectionBSD { get; set; }
        public string ElectronicStabilityControlESC { get; set; }
        public string TractionControl { get; set; }
        public string ForwardCollisionWarningFCW { get; set; }
        public string LaneDepartureWarningLDW { get; set; }
        public string LaneKeepingSupportLKS { get; set; }
        public string RearVisibilitySystemRSV { get; set; }
        public string ParkingAssist { get; set; }
        public string TPMS { get; set; }
        public string ActiveSafetySystemNote { get; set; }
        public string DynamicBrakeSupportDBS { get; set; }
        public string PedestrianAutomaticEmergencyBrakingPAEB { get; set; }
        public string AutoReverseSystemforWindowsandSunroofs { get; set; }
        public string AutomaticPedestrainAlertingSoundforHybrid { get; set; }
        public string AutomaticCrashNotificationCAN { get; set; }
        public string EventDataRecorderEDR { get; set; }
        public string KeylessIgnition { get; set; }
        public string DaytimeRunningLightDRL { get; set; }
        public string LowerBeamHeadlampLightSource { get; set; }
        public string SemiautomaticHeadlampBeamSwitching { get; set; }
        public string AdaptiveDrivingBeamADB { get; set; }
        public string SAEAutomationLevel { get; set; }
        public string BusLengthfeet { get; set; }
        public string BusFloorConfigurationType { get; set; }
        public string BusType { get; set; }
        public string OtherBusInfo { get; set; }
        public string CustomMotorcycleType { get; set; }
        public string MotorcycleSuspensionType { get; set; }
        public string MotorcycleChassisType { get; set; }
        public string OtherMotorcycleInfo { get; set; }
        public string SAEAutomationLevelupto { get; set; }
    }
}